### ISSUE TITLE
table describing completeness of the data.

### ISSUE THREAD

**Issue by aezarebski** [beoutbreakprepared/nCoV2019#22]
**Motivation:** People want to see high level summary statistics of the data and generating these is tedious.

**Idea:** extend the `entry-update-tool.R` such that it generates table of these statistics. The `xtable` package might be an easy way to do this. Editing the README programmatically seems like a bad idea, but we could write this material to a file and then include it possibly.

**Comment by aezarebski** [comment]
Regarding sources, it is probably nice to have a file with all of the unique URLs for the data. 
If we can take the root of the URL, it might be interesting to have a histogram to see where most of the data was obtained from (`table` in base R provides this).

Considering completeness of the data things get a bit more tricky, this will require the data to be validated in the way that it is by `entry-checker.R` but we already have code for that which is nice.
Perhaps a table with the following header:

```
colName,numValid,numInvalid,numMissing,numDistinct
```

which allows us to answer questions both about the quality and quantity of data in the database.

**Comment by Mougk** [comment]
Sounds super good. Let's go ahead and implement them.

**Comment by aezarebski** [comment]
@Mougk I've implemented checks for a few more fields and there is documentation surrounding how this is working. See the following commit for details: https://github.com/beoutbreakprepared/nCoV2019/commit/1cd09e45d2ec6227aa935f777db397ab5ea467f4 

It's just a lot of book keeping to implement the rest of the fields.

**Comment by aezarebski** [comment]
Done and merged see `covid19/data-dictionary.md`
