### ISSUE TITLE
Entry incorrectly displaying in Kyrgyzstan

### ISSUE THREAD

**Issue by swdomy** [beoutbreakprepared/nCoV2019#24]
The entry for "Yilin, Xinjiang, China" (which refers to Yili [Ili] Prefecture, Xinjiang, China) is currently displaying near Naryn, Kyrgyzstan. Crossing national borders should be simple enough to avoid.

**Comment by beoutbreakprepared** [comment]
Thanks - I noticed this earlier today on HealthMap actually. This is now corrected in the working database, and will be transfered over with the next database transfer and archiving. Am hoping in the next day or so.

**Comment by beoutbreakprepared** [comment]
Hopefully resolved with most recent update. Let us know if not
