### ISSUE TITLE
Missing Data on Kosovo?

### ISSUE THREAD

**Issue by celiknimani** [beoutbreakprepared/nCoV2019#35]
Data from Kosovo COVID-19 cases is missing. We have to date, 14th of March 5 confirmed infections. How can I help?

**Comment by beoutbreakprepared** [comment]
Thanks - I have added these five in now. Please keep your eyes open on this repo. We're looking to find a mechanism where people can submit pre-formatted sheets with cases.

**Comment by celiknimani** [comment]
Thanks. I can provide the trusted news sources as well if needed.
