### ISSUE TITLE
Implausible ages

### ISSUE THREAD

**Issue by beoutbreakprepared** [beoutbreakprepared/nCoV2019#4]
Motivation: Avoid implausible ages and confirm ranges are inserted in a consistent way

Idea: simple code to flag ids where ages are greater than 110(?) or not in format YY-YY

**Comment by aezarebski** [comment]
I've started working on a little checker tool for another issue, I'll put this into the functionality of that.

**Comment by aezarebski** [comment]
I've put in a PR implementing this in a checker tool. If that gets merged we can close this.
