### ISSUE TITLE
Is latestdata.csv incomplete/outdated?

### ISSUE THREAD

**Issue by edend10** [beoutbreakprepared/nCoV2019#44]
First of all, great work and thank you for providing this data!

I'm doing a simple aggregation on province, city and noticing the number isn't right for NYC.
(using python and pandas)
```
import pandas as pd
df = pd.read_csv('latestdata.csv')[['province', 'city']]
df = df.groupby(['province', 'city']).count().reset_index()
df[df['city'] == 'New York City']
```
Aggregated count in NYC comes down to 2469, whereas today cases are reported to be 20K+

On https://www.healthmap.org/covid-19/ which references your data, they show 17K which is closer to the reported numbers (at the time I'm writing the latestdata.csv has been updated 16 hours ago so their gap sense). Although I don't know if their website is augmented by another data source.

Also, the latestdata.csv  has a total of 117K rows, whereas reported cases in the world as per healthmap.org is 500K+.

Is something wrong with the way I'm looking at the data or could it be incomplete?

**Comment by giustom01** [comment]
There is something wrong with the dataset, The entire dataset has 117k records, there are 550k cases, if you select on country = 'United States' it's only got 11,364 records and there are 86,242 cases in the USA so far. I hope this can be fixed, I really need the USA stats for my company. We're using this data to determine which offices to close, we are an essential business.

**Comment by beoutbreakprepared** [comment]
Thanks for flagging - we're looking into this. There is one processing step that might have led to some cases not being present when using those filters. I will caution however that this dataset is intended to be as comprehensive as is feasible for our team, with as much specific metadata available, rather than be aligned one-to-one with the total global cases. I would suggest looking at the Johns Hopkins Github https://github.com/CSSEGISandData/COVID-19 for a system that is engineered to track cumulative counts, without the metadata of age, sex, outbreak time milestones, or more specific geography. We will retain as much as is feasible for us to do so.

**Comment by giustom01** [comment]
@beoutbreakprepared I'm fine with the entire dataset, we have global offices as well, just concentrating on USA for now. But having said that, the entire dataset only has 117k records, it should have well over 550k records and should be 600k+ after today.

**Comment by dkori** [comment]
If it helps diagnose the issue, the state of NY in the United States seems to have no cases confirmed for certain dates, while in other areas their reporting of cases seems to be pretty consistent day-to-day. 

![image](https://user-images.githubusercontent.com/10734057/77827416-e2a04080-70eb-11ea-8459-dd8e2533191a.png)

**Comment by rjf777** [comment]
is it just my copy of the 'latestdata.csv' that only has 436,549 records of the 2,479,498 cases? Is there another section? ... the latest copy is just a fifth of the cases

**Comment by tnjcook** [comment]
Is there anymore data beyond june 16?

**Comment by attwad** [comment]
@calremmel is looking into why the data isn't up to date.

**Comment by calremmel** [comment]
Hi all, update on this: the line list data source that feeds latestdata.csv is not currently being updated, so the current file is as up to date as it is going to be until that changes.

My understanding is that we'll be migrating to some other sources soon. I don't know what that will mean for accessing this particular file where it is currently, but for the time being, the most recent lines are from mid-June.

**Comment by tnjcook** [comment]
Bummer - thanks for the update!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
