### ISSUE TITLE
Reaching github recommended file size limit

### ISSUE THREAD

**Issue by attwad** [beoutbreakprepared/nCoV2019#53]
When trying to push to my repo a new version of the latest data csv file I got:

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File covid-19.data.prod.2020-04-09T111757.csv is 50.48 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

Instructions are at https://help.github.com/en/github/managing-large-files/versioning-large-files

Probably all the historical csvs should be versioned using git lfs as well.

**Comment by cathine** [comment]
Maybe can consider adding the data on HDX (https://data.humdata.org/event/covid-19#)?
