### ISSUE TITLE
Linelist Data not loading

### ISSUE THREAD

**Issue by tanaytrivedi** [beoutbreakprepared/nCoV2019#63]
Hi all,
Thanks to all the contributors for your help setting this up. I am running a project that is based on linelist data, and I noticed this morning that a few commits have made it impossible to load the data. For one, a commit ~20 hours ago by @tbrewer-healthmap has deleted the dataset archive. Furthermore, latest_data/latest_data.csv is no longer usable as it just says the following both in Github preview and the download.
<img width="1020" alt="Screen Shot 2020-05-07 at 10 08 22 AM" src="https://user-images.githubusercontent.com/19849991/81304203-c082d200-904a-11ea-9144-1703d96c9389.png">

The google sheet now points to this same link.
If I have missed some common knowledge on how to fix this, feel free to comment that below. If there is another source that I can pull this data from I am happy to work with that as well.

Thanks in advance for your help.

**Comment by RAMOSL05-GITHUB** [comment]
Having the same issue.  Wanted to access the file but looks like  latestdata.csv is not longer available.

**Comment by attwad** [comment]
the latestdata.csv file had reached the size limit that github supports (100MB) so @tbrewer-healthmap used git-lfs to track it instead (git large file system).
Github cannot display it in the UI but if you clone/fork that repository then it is still visible in your client:

```
> wc -l latest_data/latestdata.csv 
544626 latest_data/latestdata.csv
```

If checking out this repo isn't possible in your workflow (I am not sure how it looks like), then perhaps @tbrewer-healthmap can provide a gzipped version of the latestdata.csv file alongside the git-lfs tracked one. Would that help?

**Comment by fronori** [comment]
Based on your comment, I installed the git-lfs and tried to clone the repo.
And I got the following messages: 

> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> error: failed to fetch some objects from 'https://github.com/beoutbreakprepared/nCoV2019.git/info/lfs'
> 

As a result, cloned file size of latestdata.csv was just 134 bytes, including only the meta data (i.e., pointer).

I am a novice on github, especially the LFS, so I'm very glad to get directly a gzipped version of the latestdata.csv file alongside the git-lfs tracked one. Thank you for your kind help!

**Comment by tbrewer-healthmap** [comment]
Hey all, 
Sorry about the issues, I've added a compressed version of the file to the repository while we look into extending the bandwidth for proper LFS support. 
Cheers, 
`/latest_data/latestdata.tar.gz`

**Comment by RAMOSL05-GITHUB** [comment]
Thanks so much tbrewer.  I have setup Github and cloned a repository to my desktop.  How can I pull that file?

**Comment by tbrewer-healthmap** [comment]
Hey @RAMOSL05-GITHUB , 
If you cloned it after it was added, you should already have it.  Otherwise just pull the latest version as you normally would : `git pull origin master` .  The only extra step to using the data would be decompressing it first : `tar -xzvf latestdata.tar.gz` (or using your UI)

**Comment by RAMOSL05-GITHUB** [comment]
Thanks so much.

**Comment by tanaytrivedi** [comment]
Thanks for the help @tbrewer-healthmap.
