### ISSUE TITLE
Potential entry error with `travel_history_*` columns

### ISSUE THREAD

**Issue by eugejoh** [beoutbreakprepared/nCoV2019#8]
I noticed that some input for the **outside Hubei** sheet may have been switched (possible entry error) between the `travel_history_location` and `travel_history_dates` columns for the following `id` values: `146, 299, 300, 301`.

See output below

```r
library(readr)
library(dplyr)

o_hubei <- readr::read_csv("../ncov_outside_hubei.csv")

o_hubei %>% 
  filter(grepl("^[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}", travel_history_location)) %>% 
  select(id, travel_history_location, travel_history_dates, matches("^date"))

# A tibble: 4 x 3
#     id travel_history_location travel_history_dates
#   <dbl> <chr>                   <chr>               
# 1   146 15.01.2020              yes                 
# 2   299 13.01.2020              Wuhan               
# 3   300 10.01.2020              Wuhan               
# 4   301 17.01.2020              Wuhan          
```

**Comment by beoutbreakprepared** [comment]
These specific switching errors have been resolved. We have developed some scripts to ensure that date fields have dates, and are trying to routinely flag incorrect fields with greater speed. Please let me know if anything else crops up. We have been developing entry-checker.R [mainly Alex] - please feel free to add some suggested flags there
